---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantConstantBase:
  Exclude:
  - config/initializers/alert.rb
  - config/initializers/daemon_auto_start.rb
  - config/initializers/menu.rb
  - lib/redmine_tasks_scheduler/patches/tasks_scheduler_controller_patch.rb
  - redmine_tasks_scheduler.gemspec
